# docker-compose.dev.yml
version: '3.8'
services:
  soda:
    build:
      context: .
      dockerfile: Dockerfile.cpu
      args:
        DEPLOYMENT_ENV: test  # Change to "test" in CI
      target: test
    environment:
      - DEPLOYMENT_ENV=test
      - ENVIRONMENT=test
    env_file:
      - .env.test
    volumes:
      - ./:/app/          # Mount source code directory
