# docker-compose.dev.yml
version: '3.8'
services:
  soda:
    build:
      context: .
      dockerfile: Dockerfile.cpu
      args:
        DEPLOYMENT_ENV: dev
        GITHUB_TOKEN: ${GITHUB_TOKEN}
      target: development
    environment:
      - DEPLOYMENT_ENV=dev
      - ENVIRONMENT=dev
      - GITHUB_TOKEN=${GITHUB_TOKEN}  # Also pass at runtime if needed
    env_file:
      - .env.dev
    volumes:
      - ./:/app/
    command: tail -f /dev/null