# docker-compose.prod.yml
version: '3.8'
services:
  soda:
    build:
      context: .
      dockerfile: Dockerfile.cpu
      args:
        DEPLOYMENT_ENV: prod  # Change to "test" in CI
      target: production
    environment:
      - DEPLOYMENT_ENV=prod
      - ENVIRONMENT=prod
    env_file:
      - .env.prod
    volumes:
      - ./:/app/          # Mount source code directory
