version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.cpu
      target: development
    volumes:
      - .:/app
    command: ["--zip", "/app/input/sample.zip", "--config", "/app/config.yaml"]

  format:
    build:
      context: .
      dockerfile: Dockerfile.cpu
      target: formatting
    volumes:
      - .:/app

  test:
    build:
      context: .
      dockerfile: Dockerfile.cpu
      target: testing
    volumes:
      - .:/app
