# docker-compose.prod.yml
version: '3.8'
services:
  soda:
    build:
      context: .
      dockerfile: Dockerfile.cpu
      target: development
    environment:
      - DEPLOYMENT_ENV=prod
      - ENVIRONMENT=prod
    env_file:
      - .env.prod
    volumes:
      - ./:/app/          # Mount source code directory
    command: ["--zip", "/app/input/${INPUT_FILE}", "--config", "/app/config/config.yaml"]
