[build-system]
requires = ["poetry-core>=1.8.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "soda-curation"
version = "0.1.0"
description = "A professional Python package for data curation with AI capabilities"
authors = ["Dr. Jorge Abreu Vicente <jorge.abreu@embo.org>"]
license = "MIT"
readme = "README.md"
packages = [{include = "soda_curation", from = "src"}]
repository = "https://github.com/source-data/soda-curation"

[tool.poetry.dependencies]
python = ">=3.8.1,<3.11"
openai = "^1.43.0"
anthropic = "^0.34.0"
pyyaml = "^6.0.2"
python-docx = "^0.8.11"
PyPDF2 = "^3.0.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.3.0"
pytest-cov = "^4.0.0"
black = "^23.3.0"
isort = "^5.12.0"
mypy = "^1.2.0"

[tool.poetry.group.lint.dependencies]
flake8 = "^6.0.0"

[tool.poetry.scripts]
soda-curation = "soda_curation.main:main"

[tool.black]
line-length = 88
target-version = ['py38']
include = '\.pyi?$'

[tool.isort]
profile = "black"

[tool.mypy]
python_version = "3.8"
strict = true
ignore_missing_imports = true

[tool.flake8]
max-line-length = 88
extend-ignore = "E203, W503"
exclude = [
    ".git",
    "__pycache__",
    "build",
    "dist",
    ".venv",
    "venv",
]