ai: "openai"  # or "anthropic"

openai:
  api_key: "your_openai_key"
  model: "gpt-4o-2024-08-06"  
  top_p: 1.0
  temperature: 1.0
  structure_zip_assistant_id: "asst_ID"

anthropic:
  api_key: "your_anthropic_id"
  model: "claude-3-5-sonnet-20240620"  # or "claude-instant-1", etc.
  temperature: 0.7
  max_tokens_to_sample: 8000
  top_p: 1.0
  top_k: 5

object_detection:
  model_path: "data/models/panel_detection_model_no_labels.pt"
  
logging:
  level: "INFO"  # Can be DEBUG, INFO, WARNING, ERROR, CRITICAL
  file: "soda_curation.log"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  date_format: "%Y-%m-%d %H:%M:%S"

