ai: "anthropic"  # or "anthropic"

openai:
  org_key: "yout_org_key"
  api_key: "yout_api_key"
  model: "gpt-4o"  # or "gpt-3.5-turbo", etc.
  temperature: 0.7
  max_tokens: 4096
  top_p: 1.0
  frequency_penalty: 0.0
  presence_penalty: 0.0

anthropic:
  api_key: "your_api_key"
  model: "claude-3-5-sonnet-20240620"  # or "claude-instant-1", etc.
  temperature: 0.7
  max_tokens_to_sample: 8000
  top_p: 1.0
  top_k: 5