# General settings
general:
  output_directory: "/path/to/output"
  log_level: "INFO"

# AI API settings
ai_api:
  provider: "openai"  # Can be "openai" or "anthropic"
  
  openai:
    api_key: "your_openai_api_key_here"
    model: "gpt-4"
    temperature: 0.7
    max_tokens: 150

  anthropic:
    api_key: "your_anthropic_api_key_here"
    model: "claude-v1"
    temperature: 0.7
    max_tokens_to_sample: 150

# Pipeline settings
pipeline:
  steps:
    - name: "unzip"
      enabled: true
    - name: "preprocess"
      enabled: true
    - name: "object_detection"
      enabled: true
      model: "yolov10"
      confidence_threshold: 0.5
    - name: "text_extraction"
      enabled: true
    - name: "ai_analysis"
      enabled: true
    - name: "postprocess"
      enabled: true

# Object detection settings
object_detection:
  yolov10:
    weights_path: "/path/to/yolov10/weights.pt"
    device: "cuda:0"  # Use "cpu" if no GPU is available

# Text extraction settings
text_extraction:
  ocr_engine: "tesseract"
  language: "eng"

# Postprocessing settings
postprocess:
  output_format: "json"
  include_metadata: true

