ai: "openai"  # or "anthropic"

openai:
  api_key: "your_openai_key"
  model: "gpt-4o-2024-08-06"  
  top_p: 1.0
  temperature: 1.0
  structure_zip_assistant_id: "asst_ID"

anthropic:
  api_key: "your_anthropic_id"
  model: "claude-3-5-sonnet-20240620"  # or "claude-instant-1", etc.
  temperature: 0.7
  max_tokens_to_sample: 8000
  top_p: 1.0
  top_k: 5